# Generated by Django 4.2.4 on 2023-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
